lib/memes_web/router.ex
defmodule MemesWeb.Router do
  use MemesWeb, :router
  import Plug.Conn

  alias Memes.Back

  def authenticate(conn, _) do
    conn = fetch_query_params(conn)

    if (conn.params["key"] && Back.is_api_key!(conn.params["key"])) || (get_session(conn, :api_key) && Back.is_api_key!(get_session(conn, :api_key))) do
      conn
    else
      conn |> send_resp(401, "Provide API key") |> halt()
    end
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  pipeline :auth do
    plug :authenticate, nil
  end

  scope "/", MemesWeb do
    pipe_through :browser # Use the default browser stack

    get "/s", MemePageController, :memes
    get "/front/more_memes", MemePageController, :more_memes

    get "/back/authenticate", AuthenticationController, :authenticate
  end

  scope "/", MemesWeb do
    pipe_through :browser
    pipe_through :auth

    get "/front/memes/stats", MemeController, :stats

    resources "/front/memes", MemeController
    resources "/back/api_keys", APIKeyController
    resources "/back/source_sub_reddits", SourceSubRedditController
  end

  scope "/", MemesWeb do
    pipe_through :api
    pipe_through :auth

    post "/back/meme_in", MemeInController, :post
    get "/back/source_sub_reddits.json", SourceSubRedditController, :index
    get "/back/scrape_check_in", MemeInController, :check_in
  end
end

lib/memes_web/controllers/meme_page_controller.ex
defmodule MemesWeb.MemePageController do
  use MemesWeb, :controller

  alias Memes.Repo
  alias Memes.Front.Meme

  import Ecto.Query

  @memes_initial 20
  @memes_extra 20

  def memes(conn, _params) do
    memes = query() |> Repo.all()
    put_layout(conn, false)
    |> render("memes.html", memes: memes)
  end

  def more_memes(conn, %{"offset" => offset}) do
    memes = query(offset) |> Repo.all()

    put_layout(conn, false)
    |> render("some_memes.html", memes: memes)
  end

  defp query(offset \\ 0) do
    num_memes = if offset == 0, do: @memes_initial, else: @memes_extra
    from m in Meme, where: m.is_bad == false, order_by: [desc: m.score], limit: ^num_memes, offset: ^offset
  end
end

lib/memes_web/views/meme_page_view.ex
defmodule MemesWeb.MemePageView do
  use MemesWeb, :view
end

lib/memes_web/templates/meme_page/memes.html.eex
<!DOCTYPE html>
<html lang="en" style="overflow-y: hidden;">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Memes</title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <div class="title-section">
      <div class="title-message loading">
        Loading lots of memes...
      </div>
      <div class="title-message loaded" style="opacity: 0;">
        Scroll down for a stream of memes!
      </div>
    </div>

    <div class="memes">
      <%= render "some_memes.html", memes: @memes %>

      <button class="more-memes">
        Get me more memes!
      </button>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
    var more_memes_url = "<%= meme_page_path(@conn, :more_memes) %>";
    var loading = false;

    scrollTo(0, 0)

    $(document).ready(function(){
      setTimeout(function(){
        $('.title-message.loading').css({'opacity': 0})
        $('.title-message.loaded').css({'opacity': 1})
        $('.title-section').addClass('loaded')
        $('html').css({'overflow-y': 'auto'})

        var gap = 1;

        function calculate(){
          $('.meme').each(function(){
            var rows = Math.ceil($(this).find('.meme-inner').outerHeight() / 20) + gap
            $(this).css({
              "grid-row-end": "span " + rows
            })
          })
        }

        $(window).resize(calculate)

        calculate()

        $('.more-memes').click(function(){
          if(loading)
            return;
          loading = true;
          var offset = $('.memes').children().length - 1

          $.get(more_memes_url + "?offset=" + offset, function(data) {
            var content = $(data)
            $('.more-memes').before(content)
            calculate()
            loading = false;
          });
        })

        $(document).scroll(function(){
          var height = $(document.body).outerHeight();

          if((scrollY +  $(window).height()) / height > 0.8){
            $('.more-memes').click()
          }
        })
      }, 500)
    })
    </script>
  </body>
</html>

lib/memes_web/templates/meme_page/some_memes.html.eex
<%= for meme <- @memes do %>
  <div class="meme <%= if(meme.image_url, do: "image-meme", else: "text-meme") %>">
    <div class="meme-inner">
      <h2 class="meme-title"><%= meme.title %></h2>
      <!-- #<%= meme.score %> -->
      <a href="<%= meme.source_url %>" target="_blank" rel="noopener noreferrer">
        <%= if meme.image_url do %>
        <div class="image-container">
          <!-- <%= meme.image_width %>x<%= meme.image_height %> -->
          <div class="image-placeholder" style="padding-top: <%= (meme.image_height / meme.image_width) * 100 %>%;"></div>
          <img src="<%= meme.image_url %>" alt="<%= meme.title %>">
        </div>
        <% else %>
        Source
        <% end %>
      </a>
    </div>
  </div>
<% end %>