lib/memes_web/router.ex
defmodule MemesWeb.Router do
  use MemesWeb, :router
  import Plug.Conn

  alias Memes.Back

  def authenticate(conn, _) do
    conn = fetch_query_params(conn)

    if (conn.params["key"] && Back.is_api_key!(conn.params["key"])) || (get_session(conn, :api_key) && Back.is_api_key!(get_session(conn, :api_key))) do
      conn
    else
      conn |> send_resp(401, "Provide API key") |> halt()
    end
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  pipeline :auth do
    plug :authenticate, nil
  end

  scope "/", MemesWeb do
    pipe_through :browser # Use the default browser stack

    get "/s", MemePageController, :memes
    get "/front/more_memes", MemePageController, :more_memes

    get "/back/authenticate", AuthenticationController, :authenticate
  end

  scope "/", MemesWeb do
    pipe_through :browser
    pipe_through :auth

    get "/front/memes/stats", MemeController, :stats

    resources "/front/memes", MemeController
    resources "/back/api_keys", APIKeyController
    resources "/back/source_sub_reddits", SourceSubRedditController
  end

  scope "/", MemesWeb do
    pipe_through :api
    pipe_through :auth

    post "/back/meme_in", MemeInController, :post
    get "/back/source_sub_reddits.json", SourceSubRedditController, :index
    get "/back/scrape_check_in", MemeInController, :check_in
  end
end

lib/memes_web/views/layout_view.ex
defmodule MemesWeb.LayoutView do
  use MemesWeb, :view
end

lib/memes_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Memes!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>

  <body>
    <div class="container">
      <header>
        <nav role="navigation">
          <ul class="nav nav-pills">
            <li class="nav-item"><%= link "Memes", to: meme_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "API Keys", to: api_key_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "Source subreddits", to: source_sub_reddit_path(@conn, :index), class: "nav-link" %></li>
            <li class="nav-item"><%= link "Meme page", to: meme_page_path(@conn, :memes), class: "nav-link" %></li>
          </ul>
        </nav>
      </header>

      <%= if get_flash(@conn, :info) do %><p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p><% end %>
      <%= if get_flash(@conn, :error) do %><p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p><% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>